# Generated by Django 3.2.4 on 2021-07-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valhalla', '0004_auto_20210706_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='numeroSerie',
        ),
        migrations.AddField(
            model_name='producto',
            name='contrasenna',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='contrasenna'),
        ),
        migrations.AddField(
            model_name='producto',
            name='direccion',
            field=models.CharField(max_length=30, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='email',
            field=models.CharField(max_length=30, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreCompleto',
            field=models.CharField(max_length=20, null=True, verbose_name='nombreCompleto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='numeroID',
            field=models.CharField(max_length=20, null=True, primary_key=True, serialize=False, verbose_name='numeroID'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pais',
            field=models.CharField(max_length=20, null=True, verbose_name='pais'),
        ),
        migrations.AddField(
            model_name='producto',
            name='telefono',
            field=models.CharField(max_length=20, null=True, verbose_name='telefono'),
        ),
    ]
